import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar/NavBar";
import Image from "next/image";
import img from "../imgs/general/front_principal.webp";

import Section_nav_icons from "@/components/Footer/Section_nav_icons";
import { GoArrowUpRight } from "react-icons/go";
import { Nav_Footer, Nav_contact } from "@/utils/constant";
import Nav_contactCard from "@/components/Footer/nav_contact/Nav_contact";
import Nav_footer from "@/components/Footer/nav_footer/Nav_footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //
  return (
    <html lang="en">
      <body
        className={`${inter.className} overflow-y-auto  custom-scrollbar dark:custom-scrollbar-dark `}
      >
        <div className="w-full bg-light-card dark:bg-dark-principal min-h-screen ">
          <div className="fixed w-full  z-50">
            <div className="relative w-full">
              <div className=" w-[90%] 2xl:w-[70%] mx-auto h-full relative z-40">
                <nav className="w-full  mx-auto flex flex-col pt-2 ">
                  <NavBar></NavBar>
                  <div className="hidden lg:block">
                    <hr className="h-[2px] border-white" />
                  </div>
                </nav>
              </div>
              <div className="absolute w-full top-0 bg-black/40 h-[80px] lg:h-[120px] mask-linear-gradient-black  z-30 "></div>
            </div>
          </div>

          <div className="w-full h-full">{children}</div>
        </div>

        <footer className="full">
          <hr className="border-t  border-light-text-secundary dark:border-dark-card h-[1px]" />
          <div className="w-[68.5%] mx-auto">
            <div className="w-full flex flex-col lg:flex-row lg:items-center gap-4 py-8">
              <span className="verySmall_text">Modelos BMW</span>
              <span className="small_text"> Todos los modelos</span>
            </div>
          </div>
          <div className="w-full  pt-20 pb-8 bg-light-principal dark:bg-dark-card">
            <div className="w-[68.5%] h-full mx-auto">
              <div className="flex flex-col gap-8">
                <span className="verySmall_text text_color">contacto</span>

                <div className="flex flex-col gap-4">
                  {Nav_contact.map((item, index) => (
                    <div key={index}>
                      <Nav_contactCard
                        title={item.title}
                        ICON={item.ICON}
                      ></Nav_contactCard>
                    </div>
                  ))}
                </div>
                <div className="w-full flex items-center gap-8 ">
                  <Section_nav_icons></Section_nav_icons>
                </div>
              </div>
            </div>
          </div>
          <hr className="border-t  border-light-text-secundary dark:border-dark-card h-[1px]" />
          <div className="w-full py-8 dark:bg-light-principal bg-light-card">
            <div className="w-[60%] lg:w-[68%] mx-auto">
              <div className="w-full flex flex-col lg:flex-row items-center justify-between gap-8 lg:gap-0">
                <span className="text-[18px] font-light">© BMW GROUP 2024</span>

                <div className="lg:hidden flex flex-wrap items-center gap-4 justify-center">
                  {Nav_Footer.map((item, index) => (
                    <div key={index} className=" w-full">
                      <Nav_footer title={item.title}></Nav_footer>
                    </div>
                  ))}
                </div>
                <div className="w-[40%]  hidden lg:block ">
                  <div className="flex items-center gap-4 ">
                    {Nav_Footer.map((item, index) => (
                      <div key={index} className=" w-full">
                        <Nav_footer title={item.title}></Nav_footer>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
